name: v_for_v
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  country_picker: ^2.0.21
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.14.0
  
  
  
 
  
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.1


flutter:

  
  uses-material-design: true

 
  assets:
    - assets/cropped-V-logo-horiz-3.png
    

  