// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwnDkFjDNIj-zdFkEr23wwHTbMfWGkfC8',
    appId: '1:1081506638156:web:e0db39107bfc812400c7e9',
    messagingSenderId: '1081506638156',
    projectId: 'soulmate-c84a1',
    authDomain: 'soulmate-c84a1.firebaseapp.com',
    storageBucket: 'soulmate-c84a1.appspot.com',
    measurementId: 'G-VEZHT0BP3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrlMtvKph0O_JMUwk7GN6zGkvCyZ9Hp0Q',
    appId: '1:1081506638156:android:da5e6a1fe8bcb72800c7e9',
    messagingSenderId: '1081506638156',
    projectId: 'soulmate-c84a1',
    storageBucket: 'soulmate-c84a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZxt7Lug1ljUwRoXIm3J8HZrxzs_TQzvo',
    appId: '1:1081506638156:ios:446c54bf6e542dbb00c7e9',
    messagingSenderId: '1081506638156',
    projectId: 'soulmate-c84a1',
    storageBucket: 'soulmate-c84a1.appspot.com',
    iosBundleId: 'com.example.vForv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZxt7Lug1ljUwRoXIm3J8HZrxzs_TQzvo',
    appId: '1:1081506638156:ios:446c54bf6e542dbb00c7e9',
    messagingSenderId: '1081506638156',
    projectId: 'soulmate-c84a1',
    storageBucket: 'soulmate-c84a1.appspot.com',
    iosBundleId: 'com.example.vForv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwnDkFjDNIj-zdFkEr23wwHTbMfWGkfC8',
    appId: '1:1081506638156:web:a906c82799cd9ebe00c7e9',
    messagingSenderId: '1081506638156',
    projectId: 'soulmate-c84a1',
    authDomain: 'soulmate-c84a1.firebaseapp.com',
    storageBucket: 'soulmate-c84a1.appspot.com',
    measurementId: 'G-1F00ZTS20W',
  );
}
